import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { Package, Users, FileDown } from "lucide-react";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col bg-[#09090b] text-gray-200">
        <header className="flex justify-between items-center px-8 py-4 bg-[#121217] border-b border-[#27272a] shrink-0">
          <div className="flex items-center gap-8">
            <h2 className="text-xl font-bold text-white flex items-center gap-2">
              <Package size={24} className="text-[#8b5cf6]" /> CRM Dashboard
            </h2>
            <nav className="flex items-center gap-4">
              <Link href="/" className="text-sm font-semibold text-gray-400 hover:text-white transition-colors">Shipments</Link>
              <Link href="/clients" className="text-sm font-semibold text-gray-400 hover:text-white transition-colors flex items-center gap-1"><Users size={16} /> Clients</Link>
            </nav>
          </div>
          <div className="flex items-center gap-4">
            <a 
              href="/api/export" 
              download
              className="flex items-center justify-center gap-2 bg-[#27272a] hover:bg-[#3f3f46] text-white px-4 py-2 rounded-lg text-sm font-semibold transition-colors border border-[#3f3f46]"
            >
              <FileDown size={16} /> Download CSV Backup
            </a>
          </div>
        </header>
        <div className="flex-1 overflow-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}
